Add marker selection script
populationgenomics/cpg-methods pull request #1
Opened 2023-02-17 03:36 UTC by KatalinaBobowik

This script selects markers using the HGDP/1kG VDS files, which will be used to run a PCA on the PROPHECY + HGDP/1kG data. This will be the first marker table generated, followed by marker selection on the PROPHECY + HGDP + 1kG data combined. This script mirrors an earlier script run on the TOB + HGDP/1kG dataset, which can be found [here](https://github.com/populationgenomics/ancestry/blob/main/scripts/hail_batch/variant_selection/hgdp_1kg_tob_wgs_variant_selection.py). 

@lgruen if you could have a look at the VDS section, particularly adding the `GT` fields, that would be excellent.

2023-02-17 04:53 UTC, lgruen requested changes

2023-02-17 04:53 UTC, lgruen commented on scripts/marker_selection_hgdp_1kg.py
> +ONEKG = 'gs://cpg-thousand-genomes-test/vds/1-0.vds'
Can we use `dataset_path` here to parameterize this automatically for `test` vs `main`?

2023-02-17 04:53 UTC, lgruen commented on scripts/marker_selection_hgdp_1kg.py
> +    hgdp_1kg = hgdp_mt.union_cols(onekg_mt)
I think you'll want to use https://hail.is/docs/0.2/vds/hail.vds.combiner.VariantDatasetCombiner.html _before_ those expensive operations above.

That probably won't quite work on Query on Batch yet though (you're a few weeks too early) ;).

2023-02-17 04:53 UTC, lgruen commented on scripts/marker_selection_hgdp_1kg.py
> +    hgdp_1kg = hgdp_1kg.cache()
`cache` is a no-op on Query on Batch. You can use `checkpoint` instead.

2023-02-20 01:52 UTC, KatalinaBobowik commented on scripts/marker_selection_hgdp_1kg.py
> +    hgdp_1kg = hgdp_1kg.cache()
perfect, thanks!

2023-02-20 01:57 UTC, KatalinaBobowik commented on scripts/marker_selection_hgdp_1kg.py
> +ONEKG = 'gs://cpg-thousand-genomes-test/vds/1-0.vds'
given that these are paths from different datasets (`hgdp` and `thousand-genomes`), what's the best way to do that?

2023-02-20 01:59 UTC, katiedelange reviewed
Looks good from the science side, if you could just double check the AF threshold comment.

2023-02-20 01:59 UTC, katiedelange commented on scripts/marker_selection_hgdp_1kg.py
> +    # Have an allele frequency above 0.1%
It looks like you're actually using an AF threshold of 1% below - but I think this is better, as the 1KG+HGDP dataset is significantly smaller than gnomad and 0.1% doesn't correspond to very many observations (<5 alt alleles) in our case, meaning it's unlikely to be informative variation for the PCA generation.

2023-02-20 02:06 UTC, KatalinaBobowik commented on scripts/marker_selection_hgdp_1kg.py
> +    hgdp_1kg = hgdp_mt.union_cols(onekg_mt)
Is the best way to do this outside of this script then? i.e., combining the HGDP and 1kG files using the VDS combiner, then inputting it into this script?

2023-02-20 02:13 UTC, KatalinaBobowik commented on scripts/marker_selection_hgdp_1kg.py
> +    # Have an allele frequency above 0.1%
Do you mean that the comment---Have an allele frequency above 0.1%---is incorrect and the filtering is correct? Or are you suggesting a different filtering threshold?

2023-02-20 02:43 UTC, lgruen commented on scripts/marker_selection_hgdp_1kg.py
> +ONEKG = 'gs://cpg-thousand-genomes-test/vds/1-0.vds'
`dataset_path` has a `dataset` parameter: https://github.com/populationgenomics/cpg-utils/blob/1a356205582254f243cb16c8aee668af8d1719df/cpg_utils/hail_batch.py#L80

2023-02-20 02:44 UTC, lgruen commented on scripts/marker_selection_hgdp_1kg.py
> +    hgdp_1kg = hgdp_mt.union_cols(onekg_mt)
Yes, you could either do that or create a dependent Hail Batch job. You'll have to use the Dataproc wrapper for the VDS combiner for now.

2023-02-20 02:45 UTC, lgruen requested changes
See comments.

2023-02-20 03:16 UTC, katiedelange commented on scripts/marker_selection_hgdp_1kg.py
> +    # Have an allele frequency above 0.1%
I think the filtering (`(hgdp_1kg.variant_qc.AF[1] > 0.01)`) is correct (AF > 1%), and the comment should be updated to match (noting that this is a deviation from the gnomAD parameters).

2023-02-20 03:41 UTC, KatalinaBobowik commented on scripts/marker_selection_hgdp_1kg.py
> +    # Have an allele frequency above 0.1%
got it, thanks @katiedelange

2023-02-20 04:43 UTC, KatalinaBobowik commented on scripts/marker_selection_hgdp_1kg.py
> +ONEKG = 'gs://cpg-thousand-genomes-test/vds/1-0.vds'
nice, I didn't know that! I've now updated the path to take in the HGDP + 1kG VDS generated from the VDS combiner.

2023-02-20 04:44 UTC, KatalinaBobowik commented on scripts/marker_selection_hgdp_1kg.py
> +    hgdp_1kg = hgdp_mt.union_cols(onekg_mt)
I've added in a dataproc script to generate this

2023-02-20 05:09 UTC, lgruen requested changes

2023-02-20 05:09 UTC, lgruen commented on scripts/vds_combiner/hgdp_1kg/README.md
> +analysis-runner --dataset cpg-methods \
`cpg-methods` is not a dataset. We'll need to decide under which dataset we'll stored the combined data. Is this the right point to create an `ourdna` dataset?

2023-02-20 05:09 UTC, lgruen commented on scripts/marker_selection_hgdp_1kg.py
> +    hgdp_1kg = hl.vds.to_dense_mt(hl.vds.VariantDataset(hgdp_1kg.reference_data, hgdp_1kg_gt))
```suggestion
    vds = hl.vds.read_vds(HGDP_1KG)

    # Add GT field and make dense MT
    variant_data = vds.variant_data
    variant_data = variant_data.transmute_entries(GT = hl.vds.lgt_to_gt(variant_data.LGT, variant_data.LA))
    mt = hl.vds.to_dense_mt(vds)
```

2023-02-20 05:09 UTC, lgruen commented on scripts/marker_selection_hgdp_1kg.py
> +    hgdp_1kg = hgdp_1kg.checkpoint()
Doesn't checkpoint need a destination path?

2023-02-20 05:09 UTC, lgruen commented on scripts/vds_combiner/hgdp_1kg/generate_combined_hgdp_1kg_vds.py
> +    ]
These don't look like valid paths for `vds_paths` below?

2023-02-20 05:09 UTC, lgruen commented on scripts/vds_combiner/hgdp_1kg/generate_combined_hgdp_1kg_vds.py
> +        output_path=output_path('hgdp_1kg.vds'),
Will we reuse the combined dataset repeatedly? If so, computing this once and storing it makes sense. Otherwise we should store this in `tmp` and make the downstream analysis job depend on this, so it's computed on the fly when needed.

2023-02-20 05:09 UTC, lgruen commented on scripts/vds_combiner/hgdp_1kg/main.py
> +    max_age="2h",
Not sure that's enough time.

2023-02-20 05:10 UTC, lgruen commented on scripts/vds_combiner/hgdp_1kg/main.py
> +    f"generate_combined_hgdp_1kg_vds.py",
```suggestion
    "generate_combined_hgdp_1kg_vds.py",
```

2023-02-20 05:10 UTC, lgruen commented on scripts/vds_combiner/hgdp_1kg/main.py
> +    billing_project=os.getenv("HAIL_BILLING_PROJECT"), bucket=os.getenv("HAIL_BUCKET")
Nit: this file uses double quotes, while we generally use single quotes.

2023-02-20 05:57 UTC, KatalinaBobowik commented on scripts/vds_combiner/hgdp_1kg/main.py
> +    billing_project=os.getenv("HAIL_BILLING_PROJECT"), bucket=os.getenv("HAIL_BUCKET")
Fixed

2023-02-20 05:58 UTC, KatalinaBobowik commented on scripts/vds_combiner/hgdp_1kg/generate_combined_hgdp_1kg_vds.py
> +    ]
Sorry, I've now removed the quotes

2023-02-20 05:58 UTC, KatalinaBobowik commented on scripts/marker_selection_hgdp_1kg.py
> +    hgdp_1kg = hgdp_1kg.checkpoint()
yes, I've added in a path now

2023-02-20 06:04 UTC, KatalinaBobowik commented on scripts/vds_combiner/hgdp_1kg/README.md
> +analysis-runner --dataset cpg-methods \
I'm not sure of where else to store it. @katiedelange do you have any thoughts on storing this under `ourdna`?

2023-02-20 06:09 UTC, KatalinaBobowik commented on scripts/vds_combiner/hgdp_1kg/generate_combined_hgdp_1kg_vds.py
> +        output_path=output_path('hgdp_1kg.vds'),
I think it would be handy to store the combined dataset.

2023-02-20 06:27 UTC, KatalinaBobowik commented on scripts/vds_combiner/hgdp_1kg/main.py
> +    max_age="2h",
I've bumped this up a bit

2023-02-20 22:08 UTC, lgruen commented on scripts/vds_combiner/hgdp_1kg/README.md
> +analysis-runner --dataset cpg-methods \
I've created a Slack thread here for wider discussion: https://centrepopgen.slack.com/archives/C018KFBCR1C/p1676930772845849

2023-02-20 22:15 UTC, lgruen requested changes

2023-02-20 22:15 UTC, lgruen commented on scripts/marker_selection_hgdp_1kg.py
> +    mt = hl.vds.to_dense_mt(vds)
If you assign to `mt` here, you'll want to change the references to `hgdp_1kg` to `mt` below, too.

2023-02-20 22:15 UTC, lgruen commented on scripts/marker_selection_hgdp_1kg.py
> +    mt_path = output_path('hgdp_1kg_filtered_variants.mt')
Should this be versioned, too? E.g. you could define a version constant that's used for both the input VDS and the output table.

2023-02-20 22:15 UTC, lgruen commented on scripts/vds_combiner/hgdp_1kg/README.md
> +This runs a Hail query script in Dataproc using Hail Batch in order to create a combined VDS file for the HGDP + 1kG datasets. To run, use conda to install the analysis-runner, then execute the follo
```suggestion
This runs a Hail query script in Dataproc using Hail Batch in order to create a combined VDS file for the HGDP + 1kG datasets. To run, use pip to install the analysis-runner, then execute the following command:
```

2023-02-20 22:15 UTC, lgruen commented on scripts/vds_combiner/hgdp_1kg/generate_combined_hgdp_1kg_vds.py
> +        output_path=output_path('hgdp_1kg.vds'),
Ditto: should probably be versioned.

2023-02-20 22:15 UTC, lgruen commented on scripts/vds_combiner/hgdp_1kg/generate_combined_hgdp_1kg_vds.py
> +
```suggestion
```

2023-02-20 22:15 UTC, lgruen commented on scripts/vds_combiner/hgdp_1kg/generate_combined_hgdp_1kg_vds.py
> +        vds_paths=vdses,
```suggestion
        vds_paths=[HGDP, ONEKG],
```

2023-02-20 22:15 UTC, lgruen commented on scripts/vds_combiner/hgdp_1kg/main.py
> +    job_name=f'hgdp_1kg_vds',
```suggestion
    job_name='hgdp_1kg_vds',
```

2023-02-20 23:27 UTC, KatalinaBobowik commented on scripts/marker_selection_hgdp_1kg.py
> +    mt_path = output_path('hgdp_1kg_filtered_variants.mt')
doesn't `output_path` already create versioning? I have `--output-dir` set to  `vds/hgdp_1kg/v0`

2023-02-21 01:26 UTC, lgruen commented on scripts/marker_selection_hgdp_1kg.py
> +HGDP_1KG = dataset_path('vds/hgdp_1kg/v0/hgdp_1kg.vds')
Now that we have a dedicated `hgdp-1kg` dataset, you don't need to repeat that in the destination folder anymore.

2023-02-21 01:29 UTC, KatalinaBobowik commented on scripts/marker_selection_hgdp_1kg.py
> +HGDP_1KG = dataset_path('vds/hgdp_1kg/v0/hgdp_1kg.vds')
good point. Now removed

2023-02-21 02:33 UTC, KatalinaBobowik commented
@lgruen let me know if you're happy to merge. The versioning should be created automatically using the `--output-dir` + `output_path` flags, and it looks like the dataset issue is now sorted.

2023-02-21 02:43 UTC, lgruen requested changes
Did you run this in `test` to make sure it's working as expected?

2023-02-21 02:43 UTC, lgruen commented on scripts/vds_combiner/hgdp_1kg/generate_combined_hgdp_1kg_vds.py
> +        output_path=output_path('hgdp_1kg.vds'),
You can just put this under `vds/1-0.vds` to make it consistent with the HGDP / 1KG ones.

2023-02-21 02:43 UTC, lgruen commented on scripts/vds_combiner/hgdp_1kg/README.md
> +--access-level test --output-dir "vds/v0" \
(See below)

```suggestion
--access-level test --output-dir "vds" \
```

2023-02-21 02:43 UTC, lgruen commented on scripts/marker_selection_hgdp_1kg.py
> +HGDP_1KG = dataset_path('vds/v0/hgdp_1kg.vds')
```suggestion
HGDP_1KG = dataset_path('vds/v1-0.vds')
```

2023-02-21 02:43 UTC, lgruen commented on scripts/marker_selection_hgdp_1kg.py
> +    mt_path = output_path('hgdp_1kg_filtered_variants.mt')
Do we actually need to store all the variants together with the sites or would it be sufficient to just store `pruned_variant_table` instead?

2023-02-21 03:15 UTC, KatalinaBobowik commented on scripts/vds_combiner/hgdp_1kg/generate_combined_hgdp_1kg_vds.py
> +        output_path=output_path('hgdp_1kg.vds'),
At the moment I have `--output-dir "vds/v0"`. Are you suggesting it would be better to keep the versioning in the vds name itself, so instead `gs://cpg-hgdp-1kg-test/vds/1-0.vds/`? If so, I'll remove the `v0` from the `--output-dir` flag and just use `1-0.vds` for the vds name.

2023-02-21 03:17 UTC, KatalinaBobowik commented on scripts/vds_combiner/hgdp_1kg/README.md
> +--access-level test --output-dir "vds/v0" \
ah, ok this answered my question from above

2023-02-21 03:32 UTC, KatalinaBobowik commented on scripts/marker_selection_hgdp_1kg.py
> +    mt_path = output_path('hgdp_1kg_filtered_variants.mt')
Good point, the pruned variant table is sufficient here

2023-02-21 03:38 UTC, KatalinaBobowik commented on scripts/vds_combiner/hgdp_1kg/generate_combined_hgdp_1kg_vds.py
> +        output_path=output_path('hgdp_1kg.vds'),
testing this now

2023-02-21 03:38 UTC, KatalinaBobowik commented
> Did you run this in `test` to make sure it's working as expected?

testing this now

2023-02-21 10:35 UTC, KatalinaBobowik commented on scripts/vds_combiner/hgdp_1kg/generate_combined_hgdp_1kg_vds.py
> +        output_path=output_path('hgdp_1kg.vds'),
This makes sense now after reading the comments below. Fixed :)

2023-02-21 22:47 UTC, lgruen approved these changes
Nice!!

Probably a good idea to run `scripts/marker_selection_hgdp_1kg.py` with a versioned `--output` folder.

2023-02-21 22:47 UTC, lgruen commented on scripts/marker_selection_hgdp_1kg.py
> +    pruned_variant_table_path = output_path('hgdp_1kg_pruned_variants.ht')
The dataset name is already in the bucket, so you could shorten this:

```suggestion
    pruned_variant_table_path = output_path('pruned_variants.ht')
```

2023-02-22 05:02 UTC, KatalinaBobowik commented
@lgruen just flagging that I've tested the `marker_selection_hgdp_1kg.py` script and it's currently failing due to `ld_prune` not yet being supported by the service backend (see the log [here](https://batch.hail.populationgenomics.org.au/batches/421958/jobs/1)). I think the easiest way to fix this is probably switching to dataproc. What do you think?

2023-02-22 05:54 UTC, lgruen commented
Ah, that's unfortunate. LD pruning is probably just days away from being available in Query-on-Batch: https://github.com/hail-is/hail/pull/12295#issuecomment-1429629521

I'll send a quick message on Zulip to double check with the Hail team, but I suspect you're right that we'll have to use Dataproc if we want to run this right now.

2023-02-22 08:20 UTC, KatalinaBobowik commented
> Ah, that's unfortunate. LD pruning is probably just days away from being available in Query-on-Batch: [hail-is/hail#12295 (comment)](https://github.com/hail-is/hail/pull/12295#issuecomment-1429629521)
> 
> I've sent a quick message on Zulip to double check with the Hail team (https://hail.zulipchat.com/#narrow/stream/223457-Hail-Batch-support/topic/LD.20prune.20in.20QoB/near/329346164), but I suspect you're right that we'll have to use Dataproc if we want to run this right now.

Wonderful, thanks @lgruen for checking on Zulip. Until then, I'll just run using dataproc. The script should be good to go, as I ran it successfully in `test`, however let me know if you see something that's off. Otherwise, I'll merge

2023-02-22 10:58 UTC, lgruen commented
The only thing that comes to mind is that you'll probably want to add a couple of secondary workers for the Dataproc job, as otherwise this might take a long time to run on the full production dataset.

2023-02-23 01:04 UTC, merged