Create script for combining and making a sites table for an input VDS
populationgenomics/cpg-methods pull request #4
Opened 2023-03-07 06:01 UTC by KatalinaBobowik

This script combines a VDS table from an input dataset (specified by the user) and combines it with the HGDP + 1KG vds'. It then creates a sites table for the combined datasets.

2023-03-07 11:28 UTC, lgruen requested changes

2023-03-07 11:28 UTC, lgruen commented on scripts/marker_selection_all_datasets/README.md
> +This runs a Hail query script in Dataproc using Hail Batch in order to create a sites table for an input dataset and the combined HGDP + 1kG datasets. To run, use pip to install the analysis-runner,
When I read "sites table", I first thought it would output _all_ non-hom-ref loci in the combined dataset. Might be worth quickly explaining here that this is a small subset only, with a super short overview of the method.

2023-03-07 11:28 UTC, lgruen commented on scripts/marker_selection_all_datasets/marker_selection_hgdp_1kg_all_datasets.py
> +    """choosing markers for HGDP/1kG datasets according to gnomAD"""
This comment is slightly stale?

2023-03-07 11:28 UTC, lgruen commented on scripts/marker_selection_all_datasets/marker_selection_hgdp_1kg_all_datasets.py
> +    input_dataset.write(tmp_input_dataset_output)
Is this really necessary? Selecting fields shouldn't be expensive.

2023-03-07 11:28 UTC, lgruen commented on scripts/marker_selection_all_datasets/marker_selection_hgdp_1kg_all_datasets.py
> +    # downsize input variants for ld_prune
Is this comment meant to be before `sample_rows`?

2023-03-08 01:28 UTC, KatalinaBobowik commented on scripts/marker_selection_all_datasets/marker_selection_hgdp_1kg_all_datasets.py
> +    # downsize input variants for ld_prune
I've now moved this down

2023-03-08 01:29 UTC, KatalinaBobowik commented on scripts/marker_selection_all_datasets/README.md
> +This runs a Hail query script in Dataproc using Hail Batch in order to create a sites table for an input dataset and the combined HGDP + 1kG datasets. To run, use pip to install the analysis-runner,
Good point, I've added some more explanation here

2023-03-08 01:30 UTC, KatalinaBobowik commented on scripts/marker_selection_all_datasets/marker_selection_hgdp_1kg_all_datasets.py
> +    """choosing markers for HGDP/1kG datasets according to gnomAD"""
I've now updated this docstring to reflect the sites selection a bit better

2023-03-08 01:44 UTC, KatalinaBobowik commented on scripts/marker_selection_all_datasets/marker_selection_hgdp_1kg_all_datasets.py
> +    input_dataset.write(tmp_input_dataset_output)
Do you mean is selecting fields and writing them necessary? It'd be great if I could just pass the new VDSs, however I think you can only supply a path to a VDS here, right?

2023-03-09 03:36 UTC, lgruen commented on scripts/marker_selection_all_datasets/marker_selection_hgdp_1kg_all_datasets.py
> +    input_dataset.write(tmp_input_dataset_output)
Oh, you're absolutely right, sorry about that. That's a bit of an unfortunate API, but there are probably good reasons they did it that way.

2023-03-09 03:41 UTC, lgruen approved these changes

2023-03-09 03:55 UTC, merged