Add 'v' to HGDP_ONEKG VDS
populationgenomics/cpg-methods pull request #5
Opened 2023-03-10 04:22 UTC by KatalinaBobowik

After updating VDSs to include a `v` prefix, update HGDP_ONEKG file name accordingly. 

This update also includes using `dataset_path` rather than `output_path` for the pruned variants table, so that it isn't stored in the VDS folder

2023-03-10 04:35 UTC, lgruen requested changes

2023-03-10 04:35 UTC, lgruen commented on scripts/marker_selection_all_datasets/README.md
> +--access-level $ACCESS_LEVEL --output-dir "vds/hgdp-1kg" \
I think it's fine to use `output_path` below, but shouldn't `--output-dir` here be set to something outside the `vds` folder?

2023-03-10 04:43 UTC, KatalinaBobowik commented on scripts/marker_selection_all_datasets/README.md
> +--access-level $ACCESS_LEVEL --output-dir "vds/hgdp-1kg" \
I've been using `output_path` as a prefix to the combined VDSs, so in my mind it made sense to live there. Would you keep the combined VDSs in a folder outside of the vds one?

2023-03-10 05:19 UTC, lgruen commented on scripts/marker_selection_all_datasets/README.md
> +--access-level $ACCESS_LEVEL --output-dir "vds/hgdp-1kg" \
Got it, thanks! I think my confusion stems from the fact that the script is really doing two relatively unrelated things:
1. Write a combined VDS (kind of as a side effect).
2. Prune that table to generate a sparse set of markers.

Do we actually need to store / write (1) permanently or could that just be a `tmp` result, too? In case we want a permanent result, it might also be slightly cleaner to separate (1) and (2) into separate scripts, which would make the `--output-dir` semantics clearer, too.

2023-03-10 05:40 UTC, KatalinaBobowik commented on scripts/marker_selection_all_datasets/README.md
> +--access-level $ACCESS_LEVEL --output-dir "vds/hgdp-1kg" \
The output of 1 (generating the VDS) could definitely be stored in `tmp`. In that case, would the `output_path` and `temp_path` for `hl.vds.new_combiner` be the same? I'm assuming the combiner won't get upset if those values are identical?

2023-03-10 06:16 UTC, lgruen commented on scripts/marker_selection_all_datasets/README.md
> +--access-level $ACCESS_LEVEL --output-dir "vds/hgdp-1kg" \
You'll definitely want to use distinct paths for these -- the `temp_path` is just for intermediate values the combiner creates, so you wouldn't want that to collide with the actual output. Nevertheless they both could go in the `tmp` bucket.

2023-03-10 06:16 UTC, lgruen commented on scripts/marker_selection_all_datasets/README.md
> +--access-level $ACCESS_LEVEL --output-dir "vds/hgdp-1kg" \
For `--output-dir`, do you also want to specify a version?

2023-03-10 06:17 UTC, lgruen commented on scripts/marker_selection_all_datasets/README.md
> +--access-level $ACCESS_LEVEL --output-dir "vds/hgdp-1kg" \
I still think you want to the swap `dataset_path` and `output_path` usage below, as the actual output you care about is the pruned variants table.

2023-03-10 06:38 UTC, KatalinaBobowik commented on scripts/marker_selection_all_datasets/README.md
> +--access-level $ACCESS_LEVEL --output-dir "vds/hgdp-1kg" \
I've changed `output_path` to only apply to the pruned variants table, whereas the VDS tables use `dataset_path`. I've kept the `--path` parameter for the VDS input, but renamed it to `--vds-input` so it makes a bit more sense. `output-dir` can be versioned for the sites table

2023-03-13 03:05 UTC, lgruen approved these changes

2023-03-14 05:28 UTC, merged